### ISSUE TITLE
feature request: adding custom value lines

### ISSUE THREAD

**Issue by Lucas-Sichardt** [SamAmco/track-and-graph#193] opened 2022-12-29 20:50 UTC
Hi,

would it be possible to add the possibility for drawing one or more user defined horizontal lines in graphs?

One purpose could be to add a line for BMI 20 and 25 in a weight tracking graph...

Best regards,

Lucas

**Comment by SamAmco** [comment] 2023-02-05 17:33
This is a duplicate of #8 I think.

**Closed by SamAmco** 2023-02-05 17:33 UTC
