### ISSUE TITLE
option to auto-backup, either database or csv or both

### ISSUE THREAD

**Issue by pierrrek** [SamAmco/track-and-graph#59] opened 2020-12-18 11:40 UTC
You already have a backup function. It would be great if you had a check box for an automatic backup to the device that overwrites current backup file every five minutes that the app is open or when one exits the app.
I sync my device to my laptop using Syncthing and the requested level backup would enhance that so much more

**Comment by scy** [comment] 2021-11-14 14:16
Also, having an auto-backup functionality would allow the more nerdy users to create their own statistics, graphs and integrations, publish parts of the data on a regular schedule and things like that. That would be an awesome feature <3

fwiw, I’d prefer a database backup, simply because it’s more flexible and complete compared to a CSV export.

**Comment by SamAmco** [comment] 2022-01-12 18:33
Closing as duplicate of #12

**Closed by SamAmco** 2022-01-12 18:33 UTC
Labels: enhancement
