### ISSUE TITLE
Feature: Automatic/Calculated trackers

### ISSUE THREAD

**Issue by tunbridgep** [SamAmco/track-and-graph#129] opened 2021-09-07 23:37 UTC
I think it would be good to be able to have variables that we can use on graphs, but which don't take an input from the user, instead, every time a different value is tracked, they update based on a condition

Here's an example use case:

I want to have a pie chart to show me how many good nights of sleep I get compared to bad ones. Currently, doing this requires a multiple choice value. But I want to track my sleep in hours.

To accomplish this, I would create a calculated multiple choice value, where every time I track sleep hours, it takes the last value, if it's 8 or higher, it tracks "yes", otherwise it tracks "no".

Now I can generate proper line graphs for sleep hours plus I can generate a pie chart for sleep quality.

A second use case:
I want to log time spent on each individual project, so that I can see how much I've done on each, but want to track my projects on aggregate so I can easily compare how much time I spend gaming vs how much I spend doing project work. If I could create a tracker that updates itself based on when other trackers update themselves, logging their new value, I could do this.

I hope this idea makes sense

**Comment by SamAmco** [comment] 2021-09-16 09:13
Yep makes sense. I believe this is a duplicate of this issue essentially: https://github.com/SamAmco/track-and-graph/issues/69

**Closed by SamAmco** 2021-09-16 09:13 UTC
