### ISSUE TITLE
"Average Time Between" Graph type incorrect calculation

### ISSUE THREAD

**Issue by Self-Perfection** [SamAmco/track-and-graph#74] opened 2021-02-09 20:51 UTC
Let's say "Average Time Between" is created for tracking value with just two data points at 2021-01-01 15:00 and 2021-01-01 17:00

I expect this would yield result "2 hours" and yet it shows "1 hour".

I experimented a bit and it seems "Average Time Between" currently is calculated as
`(newest_value_timestamp - oldest_value_timestamp) / number_of_values`

And the correct formula should be:
`(newest_value_timestamp - oldest_value_timestamp) / (number_of_values - 1)`

**Comment by SamAmco** [comment] 2021-02-10 10:11
Good spot. I will try and take a look at this soon. Thank you.

**Comment by SamAmco** [comment] 2021-02-28 12:49
Hi @Self-Perfection . I had a look and I'm unable to reproduce this result. There is actually a test that passes in the code that runs almost the exact scenario you gave above: 

```
    @Test
    fun test_returns_duration_if_only_two_data_points() {
        //PREPARE
        val now = OffsetDateTime.now()
        val dataPoints = listOf(
            unitDataPoint(now.minusSeconds(1)),
            unitDataPoint(now)
        )

        //EXECUTE
        val ans = AverageTimeBetweenDataFactory.calculateAverageTimeBetweenOrNull(
            now,
            null,
            null,
            dataPoints
        )

        //VERIFY
        Assert.assertEquals(Duration.ofSeconds(1).toMillis().toDouble(), ans)
    }
```

There have been some changes to this algorithm over time though. Is it possible you are using an old version? You will see the version number in the top right corner of the about page. The latest is v1.10.4

**Comment by Self-Perfection** [comment] 2021-02-28 14:04
Hi. I have build 1.10.4 from F-Droid.

I can't reproduce this either, but behaviour is still confusing for me.

Right now I've created new track with just two data points:
* 2021-01-01 10:00
* 2021-01-01 12:00

I expect to get average between 2hours. Yet I get 29 days.

Apparently I was wrong and real formula used by app looks like this:
`(current_timestamp - oldest_value_timestamp) / number_of_values`

This still is not what I'd expect.

**Comment by SamAmco** [comment] 2021-02-28 18:58
The average time between takes into account the time since you last tracked something as well as the times between tracking it. This i find is generally more helpful to know. For example if i track my drinking and i stop drinking, I want to see the average decline over time.

**Comment by Self-Perfection** [comment] 2021-02-28 21:14
I see your point. In this case "Average time between" graph type should work with at least one logged value, but now it requires at least two.

My usage scenario is more like this: I'd like to know for how many days lasts charge of my electric toothbrush. So I create new tracking value and "average time between" graph from it.
I wait for the next time toothbrush needs recharge and save value, then wait again and save again. Let's say this happens after N days.
If I immediately check graph it would display N/2 days. That is far from real value.

I might decide that once I have several data points logged this is enough to calculate accurate average time between recharges and stop logging next times I recharge. But whenever I check average time between graph I get different results.

So current logic does not fit my use case.

I might add that that graph options screen adds confusion. It has option "Sample ending at" with values "Latest" and "Custom date". I'd really expect that choosing "Latest" means "latest datapoint" but not "current timestamp".

I'd suggest splitting "Sample ending at" to options "last value" for logic as I expect and "current time" for current behaviour.

**Comment by SamAmco** [comment] 2021-03-06 16:02
This is a fair point. There probably should be an option to disable the addition of the time between now and the last data point. Also you are right that you should only need 1 data point if you're including time since the last data point. I will put this on my backlog but I'm not sure when I will get to it.

**Comment by android-sam** [comment] 2023-02-16 13:27
I can't remember when but at some point i reverted the behaviour to what you desired here. I'm not sure if i want to add a checkbox for including the time since last. No one has asked for this and I would rather avoid confusing people. Also i may enable a different way to get this information when i implement functions (at some distant point :') .. Closing this issue for now.

**Closed by android-sam** 2023-02-16 13:27 UTC
Labels: bug, enhancement
