### ISSUE TITLE
Feature Request: Periodical Automatic Data Export

### ISSUE THREAD

**Issue by lil56** [SamAmco/track-and-graph#141] opened 2021-12-11 10:45 UTC
Track and Graph already features an awesome manual export function. Being able to automatically process the collected data would be even better. Here is why:
People love automation, they want to chain everything together and minimize unnecessary human interactions. Of course, one could add a complicated REST API. Instead of that, you can store the files in a mounted storage provider that uploads them, e.g. via  the DAV protocol, to your personal Nextcloud.
There software like [Analytics](https://github.com/Rello/analytics) can take care of it, you have the same functionality without networking and wake-up mechanics inside TaG itself, **keeping it lightweight**.

I am looking forward to your opinion! Maybe I can help with this improvement.

**Comment by SamAmco** [comment] 2022-01-12 19:01
Hi this is a duplicate of #12  If you want to expand on the issue then maybe do so there. I haven't got round to investigating this one yet, if you want to propose a solution then feel free but let's discuss before you start implementing anything.

**Closed by SamAmco** 2022-01-12 19:01 UTC
